---
- name: Install Jenkins Server
  hosts: jenkins
  become: yes

  roles: 
     - jenkins
     - inspec
     - terraform

- name: Install GitLab Server
  hosts: gitlab
  become: yes

  roles:
     - gitlab

- name: Install Rocket-Chat Server
  hosts: rocket
  become: yes

  roles:
    - RocketChat.Server
